### ISSUE TITLE
报错AttributeError: 'WindowsPath' object has no attribute 'seek'

### ISSUE THREAD

**Issue by bomask** [tonglei100/sweetest#10]
报错如下：

>>> 
=== RESTART: F:\sweetest\sweetest-master\example\sweetest_example\start.py ===
Traceback (most recent call last):
  File "F:\sweetest\sweetest-master\example\sweetest_example\start.py", line 24, in <module>
    sweet = Autotest(project_name, sheet_name, desired_caps, server_url)
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sweetest\autotest.py", line 39, in __init__
    self.testcase_workbook = Excel(self.testcase_file, 'r')
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sweetest\utility.py", line 16, in __init__
    self.workbook = xlrd.open_workbook(file_name)
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\__init__.py", line 122, in open_workbook
    zf = zipfile.ZipFile(filename)
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 1163, in _RealGetContents
    endrec = _EndRecData(fp)
  File "C:\Users\yangbo\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 241, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'WindowsPath' object has no attribute 'seek'
>>>

**Comment by tonglei100** [comment]
程序里使用了比较新的库 pathlib，但是 zipfile.py 这个库兼容性不太好，最好升级一下 python 吧，或者单独把 zipfile.py 更新一下
